apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: apache2-mysql-autoscaler
  labels:
    app: apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apache2-mysql
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
